version: "3"

services:
  anime_balancer:
    image: anime-balancer
    container_name: anime-service-balancer
    build:
      context: ./nginx
      dockerfile: dockerfile
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    networks:
      - anime-network

  db:
    image:  postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - anime-network

volumes:
  pg_data:

networks:
  anime-network:
    driver: bridge