name: Deploy in master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]

    steps:
      - name: Checkout nodejs
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start installation process
        run: npm i
      
      - name: Build project
        run: npm run build

      - name: Check format
        run: npm run format

      - name: Check linter
        run: npm run lint

      - name: Check Unit tests
        run: npm run test

      - name: Check E2E tests
        run: npm run test:e2e

      - name: Login to Docker Hub
        uses: docker/login-action@1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest